- name: Mises à jour des packets
  hosts: all
  become: yes


  tasks:
    - name: Mettre à jour la liste
      apt:
        update_cache: yes

    - name: Mettre à jour les packets
      apt:
        upgrade: dist

    - name: Installer dependence
      apt:
        name:
            - git
            - python3-virtualenv
            - libssl-dev
            - build-essential
            - libpython3-dev
            - python3-minimal
            - authbind
            - python3-pip
        state: present
    
    - name: Creation user cowrie
      user:
        name: cowrie
        shell: /bin/bash
        password: ""
        state: present

    - name: Creation de l'env virtuel
      command:
        cmd: virtualenv /home/cowrie/cowrie-env
        creates: "/home/cowrie/cowrie-env"

    - name: Clone du repo
      git:
        repo: 'http://github.com/micheloosterhof/cowrie'
        dest: /home/cowrie/cowrie
    
    - name: Copier conf sshd
      copy :
        src: ~/code/sshd_config
        dest: /etc/ssh/sshd_config

    - name: Règle iptables
      command: iptables -t nat -A PREROUTING -p tcp --dport 22 -j REDIRECT --to-port 22222

    - name: Chown cowrie
      path: /home/cowrie/cowrie
      owner: cowrie
      group: cowrie
      recurse: yes
